### ISSUE TITLE
merge ragel into colm repository

### ISSUE THREAD

**Issue by ehdtee** [ehdtee/colm-suite#1]
The first order of business here on github is to unify the Colm and Ragel repositories. This is a long-term strategic decision.

My next major goal with these suite of tools is to bring the language-agnostic features of Ragel to Colm. Colm is currently based on C++. It generates C++ and allows you to write a reducer for your languages in C++. I would like to extend this to additional languages in the same way Ragel 7.0 has been extended to support multiple languages. This will entail quite a bit of code sharing, particularly the intermediate language and tools.

Another reason to merge is that Ragel and Colm already share much state machine building and generation code, however the code has been cloned. I would like to eliminate these clones for the sake of code quality. This include the scanner portion of Colm, but also the LALR(1) table construction. Both of these can use libfsm.

I'm probably going to merge Ragel into the Colm repository, considering that between Ragel and Colm, Colm is really the thing that comes first. Ragel now depends on Colm. I understand this could create confusion at first, considering that at this time, most people are interested in Ragel. However, the opposite doesn't make much sense to me.

**Comment by ehdtee** [comment]
Building ragel now works. Currently adding in the test suite. Next up: docs.

**Comment by whisper-bye** [comment]
thx for your good job!
from now, can I build the latest ragel-guide-7.0.0.11.pdf?

**Comment by ehdtee** [comment]
Hi @whisper-bye, I just pushed some fixes for the pdf build. It was only building the html. Also --enable-manual and and --disable-manual should work properly now. --enabe-manual should be the default.

**Comment by whisper-bye** [comment]
@ehdtee got it. thanks for your reply.
